// Code generated by Slice Machine. DO NOT EDIT.

import BeforeAfter from './BeforeAfter';
import RichText from './RichText';

export {
	BeforeAfter,
	RichText,
};

export const components = {
	before_after: BeforeAfter,
	rich_text: RichText,
};
