import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'


import HeroBanner from '../components/HeroBanner'
import Footer from '../components/Footer'
import NavBar from '../components/NavBar'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <HeroBanner />
      <main>
        <div className="pt-10 sm:pt-16 lg:pt-8 lg:pb-0 lg:overflow-hidden">
          <div className="mx-auto max-w-7xl lg:px-8">
            <h1 className="text-3xl font-bold">
              Deez nuts
            </h1>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  )
}

export async function getServerSideProps({ previewData = {} }) {
  const client = createClient({ previewData })

  console.log('DATA!!')

  const posts = await client.getAllByType('blog-posts')
  console.log(posts)

  return { props: {} }
}

export default Home
